export {default as Navbar} from './navbar/Navbar';
export {default as Header} from './header/Header';
export {default as About} from './about/About';
export {default as Features} from './features/Features';
export {default as Download} from './download/Download';
export {default as Subscribe} from './subscribe/Subscribe';
export {default as Eligibility} from './eligibility/Eligibility';
export {default as Footer} from './footer/Footer';
export {default as ScrollToTop} from './UI/scrollToTop/ScrollToTop';